name: CI Pipeline

on:
  push:
    # In this project I mainly use the "master" branch.
    # Other branches are included only as an example
    # of a typical production CI configuration.
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw

      - name: Spotless check (code formatting)
        run: ./mvnw spotless:check

      - name: Run tests
        run: ./mvnw clean verify

      - name: Build application
        run: ./mvnw clean package

      - name: Build Docker image
        run: docker build -t coupon-service .